---
- hosts: localhost
  vars:
    type: stage
    vpc_tf:
        outputs:
           vpc_id:
               value: "" 
    vpc_name: stage
    vpc_cidr: 10.15.0.0/16
    state: absent
    teardown: true
    private_subnet_cidr: 10.15.1.0/24
    public_subnet_cidr: 10.15.2.0/24
    environment_name: stage
    enable_nat: true
    region: us-east-1
    external_cidr: 0.0.0.0/0
  roles:
    - security
    - network
