---
- hosts: localhost
  vars:
    type: stage
    vpc_tf:
        outputs:
           vpc_id:
               value: ""
           private_subnet1_id:
               value: ""
    sg_tf:
        outputs:
          internal_sg_id:
               value: "" 
    vpc_name: stage
    vpc_cidr: 10.15.0.0/16
    state: absent
    teardown: true
    private_subnet_cidr1: 10.15.1.0/24
    public_subnet_cidr1: 10.15.3.0/24
    private_subnet_cidr2: 10.15.2.0/24
    public_subnet_cidr2: 10.15.4.0/24
    environment_name: stage
    enable_nat: true
    region: us-east-1
    public_ip: false
    key_name: terraform-test 
    external_cidr: 0.0.0.0/0
  roles:
    - instances
    - security
    - network
